### ISSUE TITLE
is it possible to use PF's RDMA device once SFs are enabled for it?

### ISSUE THREAD

**Issue by htariq9436** [Mellanox/scalablefunctions#2]
Hi,

I am working with ConnectX-6 card and Linux kernel v5.13.0. As it has 2 PFs, output of _ibv_devices_ lists two RDMA devices, namely _mlx5_0_ & _mlx5_1_. Once the SFs are enabled in firmware and the _eswitch_ mode is changed to _switchdev_ for _PF1_, _mlx5_1_ loses its GIDs and hence can not be used for communication. But the following snippet from the Wiki suggests otherwise:

**When scalable function is RDMA capable, it has its own QP1, GID table and rdma resources neither shared nor stolen from the parent PCI function.**

Am I misinterpreting the above statement and seeing the expected behavior? If not do you have any idea as to why I am seeing this?

Following are the commands run before losing GIDs for _mlx5_1_:
- mlxconfig -d 0000:04:00.1 s PF_BAR2_ENABLE=0 PER_PF_NUM_SF=1 PF_TOTAL_SF=236 PF_SF_BAR_SIZE=10
- sudo devlink dev eswitch set pci/0000:04:00.1 mode switchdev

Thanks

**Comment by paravmellanox** [comment]
@htariq9436 ,

Even before creating the SFs, when you move the device to switchdev mode, mlx5_0 and mlx5_1 both will lose the GID table.
This is because PF is a switching device once you move to the switchdev mode.
In this mode, RDMA (RoCE) cannot operate. Hence there is no GID table.

you should use one of the SF or VF as communication instead of switchdev PF.

**Comment by htariq9436** [comment]
@paravmellanox,

Makes sense. Thanks for the quick response.

**Comment by htariq9436** [comment]
@paravmellanox 

Just had a little follow up to the above query. As you mentioned above, once PF is in switchdev mode it cannot be used for communication as an RDMA device. Does this hold true for the PF's net device?

Thanks

**Comment by paravmellanox** [comment]
@htariq9436 I am not lot familiar with the setups where someone assigns IP to the PF netdevice when using as the switchdev mode.
but I think it should be possible somehow, I do not know the trick for such setup.

**Comment by htariq9436** [comment]
@paravmellanox Once again thanks for the information.
